# =============================================================================
# DBT PROJECT CONFIGURATION FILE
# =============================================================================
# This is the main configuration file for your dbt project.
# It tells dbt where to find files and how to build your models.

name: 'shopify_analytics'           # Project name (lowercase, underscores only)
version: '1.0.0'                    # Semantic versioning
config-version: 2                   # dbt config version (always use 2)

# Profile defines your database connection (stored in ~/.dbt/profiles.yml)
profile: 'default'

# =============================================================================
# FILE PATHS - Where dbt looks for different file types
# =============================================================================
model-paths: ["models"]             # SQL models that create tables/views
analysis-paths: ["analyses"]        # Ad-hoc SQL queries (not materialized)
test-paths: ["tests"]               # Custom test SQL files
seed-paths: ["seeds"]               # CSV files to load into warehouse
macro-paths: ["macros"]             # Reusable SQL/Jinja functions
snapshot-paths: ["snapshots"]       # Slowly changing dimension captures

# =============================================================================
# OUTPUT PATHS
# =============================================================================
target-path: "target"               # Compiled SQL files stored here
clean-targets:                      # Directories removed by `dbt clean`
  - "target"
  - "dbt_packages"

# =============================================================================
# MODEL CONFIGURATIONS
# =============================================================================
# Configure how models are materialized (view, table, incremental, ephemeral)
# These settings cascade down the folder hierarchy

# =============================================================================
# VARIABLES
# =============================================================================
# Variables allow you to parameterize your project
# Override at runtime: dbt run --vars '{"raw_database": "prod-project"}'

vars:
  # BigQuery project where raw data is stored
  raw_database: 'your-gcp-project-id'     # 👈 CHANGE THIS to your project
  
  # BigQuery dataset where raw Shopify data lives
  raw_schema: 'raw_shopify'               # 👈 Dataset with orders table

models:
  shopify_analytics:
    # STAGING LAYER: Views for data cleaning
    staging:
      +materialized: view           # Views = fast, no storage, always fresh
      +schema: staging              # Creates models in "staging" schema
    
    # MARTS LAYER: Tables for business consumption
    marts:
      +materialized: table          # Tables = faster queries, uses storage
      +schema: marts                # Creates models in "marts" schema
