version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data from the raw seed"
    columns:
      - name: customer_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name initial"

  - name: stg_orders
    description: "Cleaned order data from the raw seed"
    columns:
      - name: order_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to stg_customers"
      - name: order_date
        description: "Date the order was placed"
      - name: order_status
        description: "Current status of the order"

  - name: stg_payments
    description: "Cleaned payment data from the raw seed"
    columns:
      - name: payment_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to stg_orders"
      - name: payment_method
        description: "Payment method used"
      - name: amount
        description: "Payment amount in dollars"
