version: 2

models:
  - name: fct_questions_summary
    description: "Fact table with daily aggregated metrics for Stack Overflow questions"
    columns:
      - name: question_date
        description: "Date of the questions"
        data_tests:
          - unique
          - not_null
      - name: total_questions
        description: "Total number of questions asked on this date"
      - name: acceptance_rate_pct
        description: "Percentage of questions with accepted answers"
      - name: avg_score
        description: "Average score of questions"

  - name: dim_tags
    description: "Dimension table for data engineering related tags"
    columns:
      - name: tag_id
        description: "Unique tag identifier"
        data_tests:
          - unique
          - not_null
      - name: tag_name
        description: "Name of the tag"
        data_tests:
          - unique
          - not_null
      - name: popularity_rank
        description: "Rank by question count (1 = most popular)"
      - name: tag_category
        description: "Category grouping for the tag"
