version: 2

models:
  - name: customers
    description: "Customer summary table with order and payment metrics"
    columns:
      - name: customer_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name initial"
      - name: first_order_date
        description: "Date of customer's first order"
      - name: most_recent_order_date
        description: "Date of customer's most recent order"
      - name: number_of_orders
        description: "Total number of orders placed"
      - name: lifetime_value
        description: "Total amount spent by customer in dollars"

  - name: orders
    description: "Order summary table with payment totals"
    columns:
      - name: order_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        data_tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: order_date
        description: "Date the order was placed"
      - name: order_status
        description: "Current status of the order"
      - name: amount
        description: "Total payment amount for the order in dollars"
      - name: payment_count
        description: "Number of payments made for the order"
